project:
  type: website

website:
  title: "Digital Epidemiology - Colombia, 12-13 September 2023"
  navbar:
    logo: /img/cgps.jpg
    left:
      - href: index.qmd
        text: Home
      - href: definitions.qmd
        text: What is Digital Epidemiology
      - text: Training materials
        menu:
          - resources.qmd
          - module3b/module3b_overview.qmd
          - microreact/microreact.qmd
          - data-flo/data-flo.qmd

  page-footer: 
    left: "This work is licensed under a Creative Commons Attribution 4.0 International License. Reuse is encouraged with acknowledgement" 
    right: 
      - icon: twitter 
        href: https://twitter.com/TheCGPS

  sidebar:
    style: "docked"
    search: true
    collapse-level: 1
    contents: 
      - section: "Module 3B"
        contents:
          - module3b/module3b_introduction.qmd
          - module3b/module3b_resources.qmd
          - module3b/module3b_references.qmd
      - section: "Microreact tutorial"
        contents:
          - microreact/microreact.qmd
          - data-flo/data-flo.qmd
          
format:
  html:
    theme:
      light: [materia, theme-light.scss]
      dark: [materia, theme-dark.scss]

editor: visual

execute:
  freeze: auto
  
sidebar:
  contents: auto

link-external-newwindow: true

